

export const RoleConstants = {
    ROLE_FARMER: "ROLE_FARMER",
    ROLE_PROCESSOR: "ROLE_PROCESSOR",
    ROLE_DISTRIBUTOR: "ROLE_DISTRIBUTOR",
    ROLE_RETAILER: "ROLE_RETAILER",
    ROLE_ADMIN:"ROLE_ADMIN",
    ROLE_ONBOARDING:"ROLE_ONBOARDING",
    ROLE_CONSUMER:"ROLE_CONSUMER",
    ROLE_GOVERNMENT:"ROLE_GOVERNMENT",
    ROLE_CVO:"ROLE_CVO",
    ROLE_SUSTAINABILITY_AUDITOR:"ROLE_SUSTAINABILITY_AUDITOR"
};