

export const RoleConstants = {
    ROLE_BIDDER: "ROLE_BIDDER",
    ROLE_BIDDER_MANAGER: "ROLE_BIDDER_MANAGER",
    ROLE_TENDER_CREATOR: "ROLE_TENDER_CREATOR",
    ROLE_TENDER_MANAGER: "ROLE_TENDER_MANAGER",
    ROLE_ADMIN:"ROLE_ADMIN",
    ROLE_ONBOARDING:"ROLE_ONBOARDING",
    ROLE_BID_EVALUATION_EXPERT:"ROLE_BID_EVALUATION_EXPERT",
    ROLE_BID_EVALUATION_CHAIRMAN:"ROLE_BID_EVALUATION_CHAIRMAN",
    ROLE_CVO:"ROLE_CVO",
    ROLE_AUDIT:"ROLE_AUDIT"
};