package com.bezkoder.spring.jwt.mongodb.models;

public enum ERole {
  ROLE_BIDDER,
  ROLE_BIDDER_MANAGER,
  ROLE_TENDER_CREATOR,
  ROLE_TENDER_MANAGER,
  ROLE_ADMIN,
  ROLE_ONBOARDING,
  ROlE_BID_EVALUATION_EXPERT,
  ROLE_BID_EVALUATION_CHAIRMAN,
  ROlE_CVO,
  ROLE_AUDIT
}
